$ErrorActionPreference='Stop'
$src=Join-Path $PSScriptRoot 'MANUAL_DE_USUARIO.md';$out=Join-Path $PSScriptRoot 'ManualUsuario.pdf'
$enc=[Text.Encoding]::GetEncoding(1252)
function Esc([string]$s){$s.Replace('\','\\').Replace('(','\(').Replace(')','\)')}
function Wrap([string]$s,[int]$n){$a=@();while($s.Length-gt$n){$p=$s.LastIndexOf(' ',$n);if($p-lt 1){$p=$n};$a+=$s.Substring(0,$p);$s=$s.Substring($p).Trim()};if($s){$a+=$s};$a}
$logical=@();foreach($l in Get-Content $src -Encoding UTF8){if($l-match '^\|[\s:|-]+\|$'){continue};$l=$l-replace '^#{1,3}\s*','' -replace '^\|','' -replace '\|$','' -replace '\|','   ' -replace '\*\*','' -replace '`','';if(!$l.Trim()){$logical+=' '}else{$prefix=if($l-match '^#'){' '}else{''};$logical+=Wrap $l 92}}
$pages=@();for($i=0;$i-lt$logical.Count;$i+=48){$pages+=,@($logical[$i..([Math]::Min($i+47,$logical.Count-1))])}
$objs=New-Object 'System.Collections.Generic.List[byte[]]';function AddObj([string]$s){$script:objs.Add($script:enc.GetBytes($s));$script:objs.Count}
$font=AddObj '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>';$bold=AddObj '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica-Bold /Encoding /WinAnsiEncoding >>'
$contentIds=@();foreach($p in $pages){$sb=New-Object Text.StringBuilder;[void]$sb.Append("BT /F1 10 Tf 48 800 Td 13 TL `n");foreach($line in $p){[void]$sb.Append("($(Esc $line)) Tj T*`n")};[void]$sb.Append('ET');$b=$enc.GetBytes($sb.ToString());$contentIds+=AddObj("<< /Length $($b.Length) >>`nstream`n$($sb.ToString())`nendstream")}
$pageStart=$objs.Count+1;$pagesId=$pageStart+$pages.Count;$catalogId=$pagesId+1;$pageIds=@();for($i=0;$i-lt$pages.Count;$i++){$id=AddObj("<< /Type /Page /Parent $pagesId 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 $font 0 R /F2 $bold 0 R >> >> /Contents $($contentIds[$i]) 0 R >>");$pageIds+=$id};$kids=($pageIds|%{"$_ 0 R"})-join' ';[void](AddObj("<< /Type /Pages /Kids [$kids] /Count $($pages.Count) >>"));[void](AddObj("<< /Type /Catalog /Pages $pagesId 0 R >>"))
$ms=New-Object IO.MemoryStream;$w=New-Object IO.BinaryWriter($ms);$w.Write($enc.GetBytes("%PDF-1.4`n%PDFGEN`n"));$offs=@(0);for($i=0;$i-lt$objs.Count;$i++){$offs+=$ms.Position;$w.Write($enc.GetBytes("$($i+1) 0 obj`n"));$w.Write($objs[$i]);$w.Write($enc.GetBytes("`nendobj`n"))};$xref=$ms.Position;$w.Write($enc.GetBytes("xref`n0 $($objs.Count+1)`n0000000000 65535 f `n"));for($i=1;$i-lt$offs.Count;$i++){$w.Write($enc.GetBytes(('{0:0000000000} 00000 n ' -f $offs[$i])+"`n"))};$w.Write($enc.GetBytes("trailer`n<< /Size $($objs.Count+1) /Root $catalogId 0 R >>`nstartxref`n$xref`n%%EOF"));[IO.File]::WriteAllBytes($out,$ms.ToArray());$w.Dispose();$ms.Dispose();$out
